#!/usr/bin/env groovy

//Jenkinsfile (Declarative Pipeline)
// Where they differ however is in syntax and flexibility. Declarative limits what is available to the user with a more strict and pre-defined structure, making it an ideal choice for simpler continuous delivery pipelines. Scripted provides very few limits, insofar that the only limits on structure and syntax tend to be defined by Groovy itself, rather than any Pipeline-specific systems, making it an ideal choice for power-users and those with more complex requirements

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '.ci/ci-linux-build.sh'
                //archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}


